// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Starter.Platform.Data;

#nullable disable

namespace Starter.Platform.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260722112320_TenantScope")]
    partial class TenantScope
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", "platform");
                });

            modelBuilder.Entity("Starter.Platform.Events.DomainEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id", "OccurredAt")
                        .HasName("pk_domain_events");

                    b.ToTable("domain_events", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Starter.Platform.Events.OutboxRow", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Lane")
                        .HasColumnType("text")
                        .HasColumnName("lane");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueued_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("PoisonedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("poisoned_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("EventId", "Lane")
                        .HasName("pk_outbox");

                    b.HasIndex("Lane", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_lane_next_attempt_at")
                        .HasFilter("delivered_at is null and poisoned_at is null");

                    b.ToTable("outbox", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_lane", "lane in ('fast','slow')");
                        });
                });

            modelBuilder.Entity("Starter.Platform.Events.ProcessedEventRow", b =>
                {
                    b.Property<string>("Consumer")
                        .HasColumnType("text")
                        .HasColumnName("consumer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Consumer", "EventId")
                        .HasName("pk_processed_events");

                    b.ToTable("processed_events", "platform");
                });

            modelBuilder.Entity("Starter.Platform.Http.IdempotencyKeyRow", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_code");

                    b.HasKey("UserId", "Key")
                        .HasName("pk_idempotency_keys");

                    b.ToTable("idempotency_keys", "platform");
                });
#pragma warning restore 612, 618
        }
    }
}
